### ISSUE TITLE
tryKeyboard authentication support

### ISSUE THREAD

**Issue by janjaali** [guidesmiths/whoosh#2]
Some server does not support password auth and require a "manually" typed password. For those servers **whoosh** fails to connect with a `Error: All configured authentication methods failed`.

[ssh2](https://github.com/mscdex/ssh2#client-methods) supports a `tryKeyboard` option which enables the handling for `keyboard-interactive` events. The support for a `tryKeyboard` option would be helpful.

**Comment by cressie176** [comment]
Hi @janjaali,
Whoosh passes options straight through the ssh2. Did you give it a try?

**Comment by janjaali** [comment]
yes I added the `tryKeyboard` option but I had no chance to react properly to the `keyboard-interactive` event since I cannot access the [connection]( https://github.com/guidesmiths/whoosh/blob/fc979fa5de559b492128bf18f8de9d90c4566108/index.js#L11) to register the event-handling.

**Comment by janjaali** [comment]
I just added a little [PR](guidesmiths/whoosh#3) to exemplify my intention.

**Comment by cressie176** [comment]
OK - I get it now. I'll take a proper look later. Thanks for raising and the PR.

**Comment by cressie176** [comment]
Published as 1.2.0. Thanks again for the PR and your help.
