### ISSUE TITLE
I don't get it

### ISSUE THREAD

**Issue by yrsealehul** [guidesmiths/whoosh#5]
I'm trying a few SFTP clients and I simply don't get it.

Firstly, Whoosh does not provide a stream interface at all - it just downloads the whole content and then gives it as a String. This is not a stream. Why are you saying its a "streaming client" when it clearly is not?

Secondly, performance is really really bad and download tests show FileZilla download my file more than 2x faster than whoosh - how is this even possible?

**Comment by cressie176** [comment]
Hi @yrsealehul 

From the Whoosh readme...

> Whoosh is an ultra thin wrapper for [SFTPStream](https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md), with the additional benefit of being able to easily stream in memory content to/from an SFTP server.

You can use all of the functions on [SFTPStream](https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md), if you want to use a purely streaming interface.

If you already have the content in memory (i.e. as a String), or want to read the content into memory, you can use `getContent` and `putContent` functions added by Whoosh.

If you're having performance concerns, I suggest trying with [SFTPStream](https://github.com/mscdex/ssh2-streams/blob/master/SFTPStream.md). Whoosh is only a very thin wrapper for this library.

**Comment by cressie176** [comment]
@yrsealehul ok to close?

**Comment by cressie176** [comment]
Closing due to lack of response
